"use client";
import Link from "next/link";
import { useState } from "react";
import { useAdminData } from "@/components/admin-provider";
import { useGameLifecycle } from "@/components/game-lifecycle-provider";
import { useMeqLanguage } from "@/components/use-meq-language";
import { useQueueData } from "@/components/queue-provider";
import { adminTranslations } from "@/lib/admin-translations";
import type { AdminEvent, AdminEventImpact, MaintenanceStatus } from "@/lib/admin-types";
import { courts } from "@/lib/court-data";
import { isGameActive } from "@/lib/game-lifecycle-rules";
import type { CourtId } from "@/lib/queue-types";

export default function AdminPage(){
 const{language,selectLanguage}=useMeqLanguage();const copy=adminTranslations[language];const admin=useAdminData();const{state:queue}=useQueueData();const{games}=useGameLifecycle();const[editing,setEditing]=useState<AdminEvent|null>(null);const[formKey,setFormKey]=useState(0);const[formError,setFormError]=useState("");
 if(!admin.ready||!admin.state)return <main className="admin-shell"><p role="status">Loading…</p></main>;
 const state=admin.state;const openCount=state.courts.filter(item=>item.isOpen).length;const waiting=queue?.entries.filter(entry=>entry.status==="WAITING").length??0;const activeGames=games.filter(isGameActive).length;const newReports=state.maintenanceReports.filter(report=>report.status==="NEW").length;
 function beginEdit(event:AdminEvent){setEditing(event);setFormKey(value=>value+1);setFormError("");document.getElementById("admin-event-form")?.scrollIntoView({behavior:"smooth"})}
 function submitEvent(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const courtIds=courts.map(court=>court.id).filter(id=>data.getAll("courtIds").includes(id)) as CourtId[];const title=String(data.get("title")??"").trim(),details=String(data.get("details")??"").trim(),date=String(data.get("date")??""),allDay=data.get("allDay")==="on",startTime=allDay?"00:00":String(data.get("startTime")??""),endTime=allDay?"23:59":String(data.get("endTime")??""),impact=String(data.get("impact")??"MEDIUM") as AdminEventImpact;if(!title||!date||!courtIds.length||(!allDay&&(!startTime||!endTime||startTime>=endTime))){setFormError(copy.required);return}const input={title,details,date,startTime,endTime,allDay,courtIds,impact};if(editing)admin.updateEvent(editing.id,input);else admin.createEvent(input);setEditing(null);setFormKey(value=>value+1);setFormError("")}
 return <main className="admin-shell"><header className="admin-header"><div><p className="section-label">ADMIN / DEVELOPMENT</p><h1>{copy.title}</h1><p>{copy.subtitle}</p></div><div className="admin-header-actions"><div className="language-switcher" role="group" aria-label={copy.language}><button type="button" className={language==="th"?"is-active":""} onClick={()=>selectLanguage("th")}>TH</button><button type="button" className={language==="en"?"is-active":""} onClick={()=>selectLanguage("en")}>EN</button></div><Link className="queue-secondary-button" href="/">← {copy.back}</Link></div></header><div className="admin-mock-banner"><b>DEV</b><span>{copy.mock}</span><button type="button" onClick={()=>{if(confirm(copy.confirmReset))admin.resetAdmin()}}>{copy.reset}</button></div>
 <section className="admin-section"><div className="admin-section-heading"><div><p className="section-label">OVERVIEW</p><h2>{copy.overview}</h2></div></div><dl className="admin-kpis"><div><dt>{copy.openCourts}</dt><dd>{openCount}/3</dd></div><div><dt>{copy.activeQueues}</dt><dd>{waiting}</dd></div><div><dt>{copy.activeGames}</dt><dd>{activeGames}</dd></div><div><dt>{copy.newReports}</dt><dd>{newReports}</dd></div></dl></section>
 <div className="admin-two-column"><section className="admin-section"><div className="admin-section-heading"><div><p className="section-label">COURTS</p><h2>{copy.courtControl}</h2><p>{copy.courtHint}</p></div></div><div className="admin-court-list">{courts.map(court=>{const setting=state.courts.find(item=>item.courtId===court.id)!;return <article key={court.id}><div><strong>{court.name}</strong><small>{court.type==="THREE_X_THREE"?"3x3":"5x5"}</small></div><button className={setting.isOpen?"is-open":"is-closed"} type="button" aria-pressed={setting.isOpen} onClick={()=>admin.setCourt(court.id,!setting.isOpen)}><i />{setting.isOpen?copy.open:copy.closed}</button></article>})}</div></section>
 <section className="admin-section"><div className="admin-section-heading"><div><p className="section-label">TARGET SCORE</p><h2>{copy.targetScores}</h2><p>{copy.targetHint}</p></div></div><div className="admin-score-settings"><article><header><strong>3x3 A / B</strong><b>{state.targetScores.threeXThree}</b></header><div>{[7,9,11].map(score=><button className={state.targetScores.threeXThree===score?"is-active":""} type="button" key={score} onClick={()=>admin.setTarget("3x3",score)}>{score}</button>)}</div></article><article><header><strong>5x5</strong><b>{state.targetScores.fiveXFive}</b></header><div>{[11,15,21].map(score=><button className={state.targetScores.fiveXFive===score?"is-active":""} type="button" key={score} onClick={()=>admin.setTarget("5x5",score)}>{score}</button>)}</div></article></div></section></div>
 <section className="admin-section admin-calendar"><div className="admin-section-heading"><div><p className="section-label">CALENDAR</p><h2>{copy.calendar}</h2><p>{copy.calendarHint}</p></div></div><div className="admin-calendar-grid"><form id="admin-event-form" className="admin-event-form" key={formKey} onSubmit={submitEvent}><h3>{editing?copy.editEvent:copy.createEvent}</h3>{formError?<p className="team-error" role="alert">{formError}</p>:null}<label><span>{copy.eventTitle}</span><input name="title" required defaultValue={editing?.title}/></label><label><span>{copy.details}</span><textarea name="details" rows={3} defaultValue={editing?.details}/></label><div className="admin-form-row"><label><span>{copy.date}</span><input type="date" name="date" required defaultValue={editing?.date}/></label><label><span>{copy.impact}</span><select name="impact" defaultValue={editing?.impact??"MEDIUM"}><option value="LOW">{copy.low}</option><option value="MEDIUM">{copy.medium}</option><option value="HIGH">{copy.high}</option></select></label></div><label className="admin-check"><input type="checkbox" name="allDay" defaultChecked={editing?.allDay}/><span>{copy.allDay}</span></label><div className="admin-form-row"><label><span>{copy.start}</span><input type="time" name="startTime" defaultValue={editing?.startTime??"09:00"}/></label><label><span>{copy.end}</span><input type="time" name="endTime" defaultValue={editing?.endTime??"10:00"}/></label></div><fieldset><legend>{copy.courts}</legend>{courts.map(court=><label className="admin-check" key={court.id}><input type="checkbox" name="courtIds" value={court.id} defaultChecked={editing?.courtIds.includes(court.id)}/><span>{court.name}</span></label>)}</fieldset><div className="admin-form-actions">{editing?<button type="button" onClick={()=>{setEditing(null);setFormKey(value=>value+1)}}>{copy.cancelEdit}</button>:null}<button className="queue-primary-button" type="submit">{copy.save}</button></div></form><div className="admin-event-list">{[...state.events].sort((a,b)=>a.date.localeCompare(b.date)).map(event=><article className={event.status==="CANCELLED"?"is-cancelled":""} key={event.id}><header><div><strong>{event.title}</strong><span>{event.status==="ACTIVE"?copy.active:copy.cancelled}</span></div><time>{event.date} · {event.allDay?copy.allDay:`${event.startTime}–${event.endTime}`}</time></header><p>{event.details}</p><small>{event.courtIds.map(id=>id.toUpperCase()).join(" · ")}</small>{event.status==="ACTIVE"?<footer><button type="button" onClick={()=>beginEdit(event)}>{copy.edit}</button><button type="button" onClick={()=>{if(confirm(copy.confirmCancel))admin.cancelEvent(event.id)}}>{copy.cancelEvent}</button></footer>:null}</article>)}</div></div></section>
 <section className="admin-section"><div className="admin-section-heading"><div><p className="section-label">MAINTENANCE</p><h2>{copy.maintenance}</h2><p>{copy.maintenanceHint}</p></div></div>{state.maintenanceReports.length===0?<p className="admin-empty">{copy.noReports}</p>:<div className="admin-report-list">{state.maintenanceReports.map(report=><article key={report.id}><div><strong>{report.courtId.toUpperCase()}</strong><span>{report.category}</span><time>{new Date(report.createdAt).toLocaleString()}</time></div><p>{report.details}</p>{report.imageName?<small>📎 {report.imageName}</small>:null}<select aria-label={`${copy.maintenance} ${report.id}`} value={report.status} onChange={event=>admin.setReportStatus(report.id,event.target.value as MaintenanceStatus)}><option value="NEW">{copy.new}</option><option value="IN_PROGRESS">{copy.inProgress}</option><option value="RESOLVED">{copy.resolved}</option></select></article>)}</div>}</section></main>
}
