"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { useCheckIn } from "./check-in-provider";
import { useMeqLanguage } from "./use-meq-language";
import { checkInTranslations } from "@/lib/check-in-translations";
import { getCheckInError } from "@/lib/check-in-error-copy";
import { getCheckInTimeRemaining } from "@/lib/check-in-rules";
import type { CheckInError, LocationStatus, TeamCheckInSession } from "@/lib/check-in-types";
import type { CourtId } from "@/lib/queue-types";
import { useGameLifecycle } from "./game-lifecycle-provider";
import { getActiveGameForCourt } from "@/lib/game-lifecycle-rules";

function Countdown({session,label,expired}:{session:TeamCheckInSession;label:string;expired:string}){const[now,setNow]=useState(0);useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[]);const seconds=getCheckInTimeRemaining(session.checkInDeadline,now||Date.parse(session.calledAt));const value=`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;return <div className={`checkin-countdown ${seconds===0?"is-expired":""}`} role="timer" aria-live="polite"><small>{seconds===0?expired:label}</small><strong>{value}</strong></div>}

export function CheckInPanel({courtId}:{courtId:CourtId}){
 const{language}=useMeqLanguage();const copy=checkInTranslations[language];const{state,activeMockUserId,callNextTeam,checkIn,setActiveMockUser,setMockUserLocation,shortenDeadline,expireNow,startMockGame,resetCheckInData}=useCheckIn();const[error,setError]=useState<CheckInError|null>(null);const[announcement,setAnnouncement]=useState("");
 const{games}=useGameLifecycle();
 if(!state)return null;
 const sessions=state.sessions.filter((s)=>s.courtId===courtId&&s.status!=="PLAYING");const actionable=[...sessions].reverse().find((s)=>s.status==="CALLED"||s.status==="CHECKING_IN")??null;const game=getActiveGameForCourt(games,courtId);
 function run(result:ReturnType<typeof checkIn>){if(result.ok){setError(null);setAnnouncement(result.session?.status==="READY_TO_PLAY"?copy.teamReady:copy.checkedIn)}else setError(result.error)}
 function locationLabel(status:LocationStatus){return status==="WITHIN_RANGE"?copy.withinRange:status==="OUT_OF_RANGE"?copy.outOfRange:copy.permissionDenied}
 return <section className="checkin-section" id="check-in" aria-labelledby="checkin-heading"><div className="section-heading"><div><p className="section-label">{copy.sectionLabel}</p><h2 id="checkin-heading">{copy.title}</h2></div><p>{copy.mockLocationNotice}</p></div><div className="sr-live" aria-live="polite">{announcement}</div>
 {game?<article className="mock-game-card"><span>{copy.gamePlaying}</span><div><strong>{game.teamA.teamName}</strong><b>VS</b><strong>{game.teamB.teamName}</strong></div><small>{copy.target} {game.targetScore} {copy.points}</small></article>:null}
 {error?<div className="team-error" role="alert">{getCheckInError(error,copy)}</div>:null}
 <div className="checkin-cards">{sessions.length===0?<div className="empty-queue">{copy.noCalledTeam}</div>:sessions.map((session)=>{const isMember=session.members.some((m)=>m.id===activeMockUserId);const isCaptain=(session.captainUserId??session.members[0]?.id)===activeMockUserId;const location=activeMockUserId?(state.locations[activeMockUserId]??"WITHIN_RANGE"):"WITHIN_RANGE";return <article className={`checkin-card status-${session.status.toLowerCase()}`} key={session.id}><header><div><small>{copy.calledTeam}</small><h3>{session.teamName}</h3><span>{copy[`status_${session.status}` as keyof typeof copy]}</span></div>{session.status!=="MISSED_QUEUE"&&session.status!=="READY_TO_PLAY"?<Countdown session={session} label={copy.timeRemaining} expired={copy.expired}/>:null}</header><div className="checkin-progress"><strong>{session.checkIns.length}/{session.members.length}</strong><span>{copy.readyCount}</span><i><b style={{width:`${session.members.length?session.checkIns.length/session.members.length*100:0}%`}}/></i></div>{isMember?<ul className="checkin-member-list">{session.members.map((member)=>{const ready=session.checkIns.some((c)=>c.userId===member.id);const memberLocation=state.locations[member.id]??"WITHIN_RANGE";return <li className={member.id===activeMockUserId?"is-current":""} key={member.id}><span className="member-avatar">{member.initials}</span><div><strong>{member.displayName}</strong><small>{locationLabel(memberLocation)}</small></div><span>{ready?`✓ ${copy.checkedIn}`:`○ ${copy.notReady}`}</span></li>})}</ul>:null}{session.status==="MISSED_QUEUE"?<div className="missed-message"><strong>{copy.missed}</strong><p>{copy.missedHint}</p><Link href="#queue">{copy.rejoin}</Link></div>:isCaptain&&session.status!=="READY_TO_PLAY"?<button className="queue-primary-button" type="button" onClick={()=>run(checkIn(session.id))}>{copy.confirmTeamReady}</button>:isMember&&session.status!=="READY_TO_PLAY"?<div className="team-ready-message is-waiting">{copy.waitingCaptain}</div>:session.status==="READY_TO_PLAY"?<div className="team-ready-message">✓ {copy.teamReady}</div>:null}{isMember?<small className={`member-location location-${location.toLowerCase()}`}>{copy.location}: {locationLabel(location)}</small>:null}</article>})}</div>
 {process.env.NODE_ENV==="development"?<aside className="checkin-dev-panel"><header><div><span>DEV</span><strong>{copy.devTitle}</strong><small>{copy.devHint}</small></div><button type="button" onClick={resetCheckInData}>{copy.reset}</button></header><div className="dev-control-grid"><button type="button" onClick={()=>{const r=callNextTeam(courtId);if(!r.ok)setError(r.error)}}>{copy.callNext}</button><button type="button" disabled={!actionable} onClick={()=>actionable&&shortenDeadline(actionable.id,10)}>{copy.shorten}</button><button type="button" disabled={!actionable} onClick={()=>actionable&&expireNow(actionable.id)}>{copy.expireNow}</button><button type="button" onClick={()=>{const r=startMockGame(courtId);if(!r.ok)setError(r.error)}}>{copy.startGame}</button></div>{actionable?<div className="dev-user-controls"><label>{copy.switchUser}<select value={activeMockUserId??""} onChange={(e)=>setActiveMockUser(e.target.value)}>{actionable.members.map((m)=><option value={m.id} key={m.id}>{m.displayName}</option>)}</select></label><div role="group" aria-label={copy.location}>{(["WITHIN_RANGE","OUT_OF_RANGE","PERMISSION_DENIED"] as LocationStatus[]).map((status)=><button className={(state.locations[activeMockUserId??""]??"WITHIN_RANGE")===status?"is-active":""} type="button" key={status} onClick={()=>activeMockUserId&&setMockUserLocation(activeMockUserId,status)}>{locationLabel(status)}</button>)}</div></div>:null}</aside>:null}</section>
}
