"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";
import { useQueueData } from "./queue-provider";
import { useTeamData } from "./team-provider";
import { getCourtById } from "@/lib/court-data";
import { beginTeamCheckIn, callNextTeam as callNextTeamRule, cancelMemberCheckIn as cancelRule, confirmTeamReady, expireCheckInIfNeeded, getCheckInTimeRemaining, releaseOrphanCheckInEntries, startMockGame as startGameRule } from "@/lib/check-in-rules";
import { LocalStorageCheckInRepository, type CheckInRepository } from "@/lib/check-in-repository";
import { LocalStorageNotificationRepository, type NotificationRepository } from "@/lib/notification-repository";
import type { CheckInDataState, CheckInResult, LocationStatus, TeamCheckInSession } from "@/lib/check-in-types";
import type { MockNotification, NotificationDataState, NotificationKind } from "@/lib/notification-types";
import type { CourtId, QueueTeamSnapshot } from "@/lib/queue-types";
import { useAdminData } from "./admin-provider";
import { getAdminCourt } from "@/lib/admin-rules";

type ContextValue={ready:boolean;state:CheckInDataState|null;notifications:NotificationDataState|null;activeMockUserId:string|null;callNextTeam(courtId:CourtId):CheckInResult;checkIn(sessionId:string):CheckInResult;cancelCheckIn(sessionId:string):CheckInResult;setActiveMockUser(userId:string):void;setMockUserLocation(userId:string,status:LocationStatus):void;shortenDeadline(sessionId:string,seconds:number):void;expireNow(sessionId:string):void;startMockGame(courtId:CourtId):CheckInResult;replaceCheckInState(state:CheckInDataState):void;resetCheckInData():void};
const CheckInContext=createContext<ContextValue|null>(null);

export function CheckInProvider({children,repository,notificationRepository}:{children:React.ReactNode;repository?:CheckInRepository;notificationRepository?:NotificationRepository}){
  const repo=useMemo(()=>repository??new LocalStorageCheckInRepository(),[repository]);
  const notificationRepo=useMemo(()=>notificationRepository??new LocalStorageNotificationRepository(),[notificationRepository]);
  const [state,setState]=useState<CheckInDataState|null>(null); const [notifications,setNotifications]=useState<NotificationDataState|null>(null);
  const {state:queueState,replaceQueueState,resetQueueData}=useQueueData(); const {state:teamState,currentUser}=useTeamData();
  const {state:adminState}=useAdminData();
  useEffect(()=>{const frame=requestAnimationFrame(()=>{setState(repo.load());setNotifications(notificationRepo.load());});return()=>cancelAnimationFrame(frame);},[repo,notificationRepo]);

  function addNotification(kind:NotificationKind,courtId:CourtId,teamId?:string){const item:MockNotification={id:`notification-${crypto.randomUUID()}`,kind,courtId,teamId,createdAt:new Date().toISOString()};setNotifications(notificationRepo.add(item));}
  function commit(next:CheckInDataState,nextQueue=queueState){repo.save(next);setState(next);if(nextQueue)replaceQueueState(nextQueue);}
  function resolveTeam(teamId:string):QueueTeamSnapshot|null {const mock=queueState?.mockTeams.find((team)=>team.id===teamId);if(mock)return{...mock,captainUserId:mock.captainUserId??mock.members[0]?.id};const team=teamState?.teams.find((item)=>item.id===teamId);if(!team)return null;return{id:team.id,name:team.name,type:team.type,captainUserId:team.captainUserId,memberCount:team.members.length,members:team.members.flatMap((member)=>{const user=teamState?.users.find((item)=>item.id===member.userId);return user?[{id:user.id,displayName:user.displayName,initials:user.initials}]:[]})};}
  function callNextTeam(courtId:CourtId):CheckInResult {if(!state||!queueState)return{ok:false,error:"NO_WAITING_TEAM"};const hasHolding=queueState.entries.some((entry)=>entry.courtId===courtId&&entry.status==="HOLDING_COURT");const hasReturning=queueState.entries.some((entry)=>entry.courtId===courtId&&entry.status==="RETURNING_CHAMPION");if(hasHolding&&hasReturning)return startMockGame(courtId);const nowIso=new Date().toISOString();const normalizedQueue=releaseOrphanCheckInEntries(queueState,state,courtId,nowIso);const head=normalizedQueue.entries.filter((e)=>e.courtId===courtId&&e.status==="WAITING").sort((a,b)=>a.position-b.position)[0];const called=callNextTeamRule(normalizedQueue,state,courtId,head?resolveTeam(head.teamId):null,nowIso);if(!called.result.ok){if(called.queueState!==queueState)commit(called.checkInState,called.queueState);return called.result}const begun=beginTeamCheckIn(called.queueState,called.checkInState,called.result.session!.id);commit(begun.checkInState,begun.queueState);addNotification("TEAM_CALLED",courtId,called.result.session!.teamId);return begun.result;}
  function checkIn(sessionId:string):CheckInResult {if(!state||!queueState)return{ok:false,error:"SESSION_NOT_FOUND"};const userId=state.activeMockUserId??currentUser?.id;if(!userId)return{ok:false,error:"MEMBER_NOT_IN_TEAM"};const transition=confirmTeamReady(queueState,state,sessionId,userId,state.locations,new Date().toISOString());if(transition.result.ok){commit(transition.checkInState,transition.queueState);const readySession=transition.result.session;if(readySession?.status==="READY_TO_PLAY"){addNotification("TEAM_READY",readySession.courtId,readySession.teamId);const readyCount=transition.checkInState.sessions.filter((session)=>session.courtId===readySession.courtId&&session.status==="READY_TO_PLAY").length;if(readyCount>=2)addNotification("GAME_READY",readySession.courtId);}}return transition.result;}
  function cancelCheckIn(sessionId:string):CheckInResult {if(!state||!queueState)return{ok:false,error:"SESSION_NOT_FOUND"};const userId=state.activeMockUserId??currentUser?.id;if(!userId)return{ok:false,error:"MEMBER_NOT_IN_TEAM"};const transition=cancelRule(queueState,state,sessionId,userId);if(transition.result.ok)commit(transition.checkInState,transition.queueState);return transition.result;}
  function setActiveMockUser(userId:string){if(state)commit({...state,activeMockUserId:userId},queueState);}
  function setMockUserLocation(userId:string,status:LocationStatus){if(state)commit({...state,locations:{...state.locations,[userId]:status}},queueState);}
  function shortenDeadline(sessionId:string,seconds:number){if(!state||!queueState)return;const deadline=new Date(Date.now()+seconds*1000).toISOString();commit({...state,sessions:state.sessions.map((s)=>s.id===sessionId?{...s,checkInDeadline:deadline}:s)}, {...queueState,entries:queueState.entries.map((e)=>state.sessions.find((s)=>s.id===sessionId)?.queueEntryId===e.id?{...e,checkInDeadline:deadline}:e)});}
  function expireNow(sessionId:string){if(!state||!queueState)return;const deadline=new Date(Date.now()-1000).toISOString();const staged={...state,sessions:state.sessions.map((s)=>s.id===sessionId?{...s,checkInDeadline:deadline}:s)};const transition=expireCheckInIfNeeded(queueState,staged,new Date().toISOString());commit(transition.checkInState,transition.queueState);const missed=transition.checkInState.sessions.find((s)=>s.id===sessionId&&s.status==="MISSED_QUEUE");if(missed)addNotification("MISSED_QUEUE",missed.courtId,missed.teamId);}
  function startMockGame(courtId:CourtId):CheckInResult {if(!state||!queueState)return{ok:false,error:"NOT_ENOUGH_READY_TEAMS"};const baseCourt=getCourtById(courtId);const court=baseCourt&&adminState?getAdminCourt(adminState,baseCourt):baseCourt;if(!court)return{ok:false,error:"NOT_ENOUGH_READY_TEAMS"};const holdingEntry=queueState.entries.find((entry)=>entry.courtId===courtId&&entry.status==="HOLDING_COURT");const returningEntry=queueState.entries.find((entry)=>entry.courtId===courtId&&entry.status==="RETURNING_CHAMPION");const transition=startGameRule(queueState,state,court,new Date().toISOString(),holdingEntry?resolveTeam(holdingEntry.teamId):null,returningEntry?resolveTeam(returningEntry.teamId):null);if(transition.result.ok)commit(transition.checkInState,transition.queueState);return transition.result;}
  function resetCheckInData(){resetQueueData();setState(repo.reset());setNotifications(notificationRepo.reset());}
  function replaceCheckInState(next:CheckInDataState){repo.save(next);setState(next)}

  // The interval intentionally rebinds whenever persisted state changes.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(()=>{if(!state||!queueState)return;const timer=window.setInterval(()=>{const now=new Date();const transition=expireCheckInIfNeeded(queueState,state,now.toISOString());const expired=transition.checkInState.sessions.filter((s)=>s.status==="MISSED_QUEUE"&&!state.sessions.some((old)=>old.id===s.id&&old.status==="MISSED_QUEUE"));if(expired.length){commit(transition.checkInState,transition.queueState);expired.forEach((s)=>addNotification("MISSED_QUEUE",s.courtId,s.teamId));return;}for(const session of state.sessions.filter((s)=>s.status==="CALLED"||s.status==="CHECKING_IN")){const remaining=getCheckInTimeRemaining(session.checkInDeadline,now.getTime());const exists=notifications?.items.some((n)=>n.kind==="ONE_MINUTE_LEFT"&&n.teamId===session.teamId);if(remaining>0&&remaining<=60&&!exists)addNotification("ONE_MINUTE_LEFT",session.courtId,session.teamId);}},1000);return()=>clearInterval(timer);},[state,queueState,notifications]);

  return <CheckInContext.Provider value={{ready:Boolean(state&&notifications),state,notifications,activeMockUserId:state?.activeMockUserId??currentUser?.id??null,callNextTeam,checkIn,cancelCheckIn,setActiveMockUser,setMockUserLocation,shortenDeadline,expireNow,startMockGame,replaceCheckInState,resetCheckInData}}>{children}</CheckInContext.Provider>;
}
export function useCheckIn(){const context=useContext(CheckInContext);if(!context)throw new Error("useCheckIn must be used inside CheckInProvider");return context;}
export function getLatestCourtSession(sessions:TeamCheckInSession[],courtId:CourtId){return sessions.filter((s)=>s.courtId===courtId).at(-1)??null;}
