"use client";
import { createContext,useContext,useEffect,useMemo,useState } from "react";
import { useQueueData } from "./queue-provider";
import { useCheckIn } from "./check-in-provider";
import { LocalStorageGameRepository,LocalStoragePlayerStatisticsRepository,LocalStoragePostGameDecisionRepository,LocalStorageScoreSubmissionRepository,type GameRepository,type PlayerStatisticsRepository,type PostGameDecisionRepository,type ScoreSubmissionRepository } from "@/lib/game-repositories";
import { LocalStorageNotificationRepository } from "@/lib/notification-repository";
import { cancelEndGameRequest,chooseLeaveQueue,chooseRequeue,chooseWinnerContinuation,closeGameCheckInSession,expireRequeueDecisionIfNeeded,processSubmittedGame,requestEndGame,confirmEndGame,saveScoreDraft,submitTeamScores,synchronizeHoldingWinnerEntry } from "@/lib/game-lifecycle-rules";
import type { GameLifecycle,GameLifecycleError,PlayerGameHistory,PostGameDecision,ScoreSubmission,ScoreSubmitResult } from "@/lib/game-lifecycle-types";
import type { NotificationKind } from "@/lib/notification-types";
type Versioned<T>={version:1;items:T[]};
type Context={ready:boolean;games:GameLifecycle[];submissions:ScoreSubmission[];history:PlayerGameHistory[];decisions:PostGameDecision[];activeUserId:string|null;setActiveUser(id:string):void;requestEnd(gameId:string):GameLifecycleError|null;cancelEnd(gameId:string):GameLifecycleError|null;confirmEnd(gameId:string):GameLifecycleError|null;saveDraft(gameId:string,teamId:string,scores:Record<string,number>):GameLifecycleError|null;submitScores(gameId:string,teamId:string):ScoreSubmitResult;chooseWinnerContinue(gameId:string):GameLifecycleError|null;chooseWinnerLeave(gameId:string):GameLifecycleError|null;chooseRequeue(gameId:string):GameLifecycleError|null;chooseLeave(gameId:string):GameLifecycleError|null;shortenDecision(gameId:string,seconds:number):void;expireDecision(gameId:string):void;setScenario(gameId:string,mode:"FIRST_WIN"|"SECOND_WIN"|"REST_GAME"|"RETURNING"):void;resetLifecycle():void};
const Ctx=createContext<Context|null>(null);
export function GameLifecycleProvider({children,gameRepository,scoreRepository,statisticsRepository,decisionRepository}:{children:React.ReactNode;gameRepository?:GameRepository;scoreRepository?:ScoreSubmissionRepository;statisticsRepository?:PlayerStatisticsRepository;decisionRepository?:PostGameDecisionRepository}){const gameRepo=useMemo(()=>gameRepository??new LocalStorageGameRepository(),[gameRepository]);const scoreRepo=useMemo(()=>scoreRepository??new LocalStorageScoreSubmissionRepository(),[scoreRepository]);const statsRepo=useMemo(()=>statisticsRepository??new LocalStoragePlayerStatisticsRepository(),[statisticsRepository]);const decisionRepo=useMemo(()=>decisionRepository??new LocalStoragePostGameDecisionRepository(),[decisionRepository]);const notificationRepo=useMemo(()=>new LocalStorageNotificationRepository(),[]);const[gameState,setGameState]=useState<Versioned<GameLifecycle>|null>(null),[scoreState,setScoreState]=useState<Versioned<ScoreSubmission>|null>(null),[historyState,setHistoryState]=useState<Versioned<PlayerGameHistory>|null>(null),[decisionState,setDecisionState]=useState<Versioned<PostGameDecision>|null>(null),[activeUserId,setActiveUser]=useState<string|null>(null);const{state:queueState,replaceQueueState}=useQueueData();
 const{state:checkInState,replaceCheckInState}=useCheckIn();
 useEffect(()=>{const f=requestAnimationFrame(()=>{const games=gameRepo.load();setGameState(games);setScoreState(scoreRepo.load());setHistoryState(statsRepo.load());setDecisionState(decisionRepo.load());setActiveUser(games.items[0]?.teamA.captainUserId??null)});return()=>cancelAnimationFrame(f)},[gameRepo,scoreRepo,statsRepo,decisionRepo]);
 // Synchronize newly started check-in games into the lifecycle repository.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{if(!gameState||!checkInState)return;const existing=new Set(gameState.items.map(game=>game.id));const previousWinnerStreak=(teamId:string,courtId:GameLifecycle["courtId"])=>gameState.items.filter((item)=>item.status==="COMPLETED"&&item.courtId===courtId&&item.winnerTeamId===teamId).sort((a,b)=>Date.parse(b.completedAt??"")-Date.parse(a.completedAt??""))[0]?.postGame?.winnerConsecutiveWins??0;const incoming:GameLifecycle[]=checkInState.games.filter(game=>!existing.has(game.id)).map(game=>({id:game.id,courtId:game.courtId,teamA:{teamId:game.teamAId,teamName:game.teamAName,captainUserId:game.teamAMembers[0]?.id??"",members:game.teamAMembers,consecutiveWinsBefore:game.teamAConsecutiveWinsBefore??previousWinnerStreak(game.teamAId,game.courtId)},teamB:{teamId:game.teamBId,teamName:game.teamBName,captainUserId:game.teamBMembers[0]?.id??"",members:game.teamBMembers,consecutiveWinsBefore:game.teamBConsecutiveWinsBefore??previousWinnerStreak(game.teamBId,game.courtId)},targetScore:game.targetScore,startedAt:game.startedAt,status:"PLAYING",isRestGame:game.isRestGame??false,...(game.restingChampionTeamId?{restingChampionTeamId:game.restingChampionTeamId}:{})}));if(!incoming.length)return;const next={version:1 as const,items:[...gameState.items,...incoming]};gameRepo.save(next);setGameState(next)},[checkInState,gameState,gameRepo]);
 // Migrate stale v1 check-in data: completed lifecycle games can never remain active check-ins.
 useEffect(()=>{if(!gameState||!checkInState)return;const completed=gameState.items.filter((game)=>game.status==="COMPLETED");const synchronized=completed.reduce(closeGameCheckInSession,checkInState);if(synchronized.games.length!==checkInState.games.length||synchronized.sessions.length!==checkInState.sessions.length)replaceCheckInState(synchronized)},[gameState,checkInState,replaceCheckInState]);
 useEffect(()=>{if(!gameState||!queueState)return;const synchronized=synchronizeHoldingWinnerEntry(gameState.items,queueState,new Date().toISOString());if(synchronized!==queueState)replaceQueueState(synchronized)},[gameState,queueState,replaceQueueState]);
 function saveGames(items:GameLifecycle[]){const next={version:1 as const,items};gameRepo.save(next);setGameState(next)}function saveScores(items:ScoreSubmission[]){const next={version:1 as const,items};scoreRepo.save(next);setScoreState(next)}function saveHistory(items:PlayerGameHistory[]){const next={version:1 as const,items};statsRepo.save(next);setHistoryState(next)}function saveDecisions(items:PostGameDecision[]){const next={version:1 as const,items};decisionRepo.save(next);setDecisionState(next)}function notify(kind:NotificationKind,courtId:GameLifecycle["courtId"],teamId?:string){notificationRepo.add({id:`notification-${crypto.randomUUID()}`,kind,courtId,teamId,createdAt:new Date().toISOString()})}
 function mutateEnd(gameId:string,fn:(game:GameLifecycle,user:string,now:string)=>ReturnType<typeof requestEndGame>){if(!gameState||!activeUserId)return"GAME_NOT_FOUND";const game=gameState.items.find(g=>g.id===gameId);if(!game)return"GAME_NOT_FOUND";const result=fn(game,activeUserId,new Date().toISOString());if(!result.ok)return result.error;saveGames(gameState.items.map(g=>g.id===gameId?result.game:g));return null}
 function requestEnd(gameId:string){return mutateEnd(gameId,requestEndGame)}function confirmEnd(gameId:string){return mutateEnd(gameId,confirmEndGame)}function cancelEnd(gameId:string){if(!gameState||!activeUserId)return"GAME_NOT_FOUND";const game=gameState.items.find(g=>g.id===gameId);if(!game)return"GAME_NOT_FOUND";const result=cancelEndGameRequest(game,activeUserId);if(!result.ok)return result.error;saveGames(gameState.items.map(g=>g.id===gameId?result.game:g));return null}
 function saveDraft(gameId:string,teamId:string,scores:Record<string,number>){if(!gameState||!scoreState||!activeUserId)return"GAME_NOT_FOUND";const game=gameState.items.find(g=>g.id===gameId);if(!game)return"GAME_NOT_FOUND";const latest=scoreRepo.load();const existing=latest.items.find(s=>s.gameId===gameId&&s.teamId===teamId);const result=saveScoreDraft(game,existing,teamId,activeUserId,scores,new Date().toISOString());if(result.error)return result.error;saveScores([...latest.items.filter(s=>s.id!==result.submission!.id),result.submission!]);return null}
 function submitScores(gameId:string,teamId:string):ScoreSubmitResult{if(!gameState||!scoreState||!historyState||!decisionState||!queueState||!activeUserId)return{error:"GAME_NOT_FOUND"};const latestGames=gameRepo.load(),latestScores=scoreRepo.load(),latestHistory=statsRepo.load(),latestDecisions=decisionRepo.load();const game=latestGames.items.find(g=>g.id===gameId),submission=latestScores.items.find(s=>s.gameId===gameId&&s.teamId===teamId);if(!game||!submission)return{error:"INCOMPLETE_PLAYERS"};const submitted=submitTeamScores(game,submission,activeUserId,new Date().toISOString());if(submitted.error)return{error:submitted.error};const submissions=[...latestScores.items.filter(s=>!(s.gameId===gameId&&s.teamId===teamId)),submitted.submission!];saveScores(submissions);const a=submissions.find(s=>s.gameId===gameId&&s.teamId===game.teamA.teamId),b=submissions.find(s=>s.gameId===gameId&&s.teamId===game.teamB.teamId);if(a?.status!=="SUBMITTED"||b?.status!=="SUBMITTED")return{outcome:"WAITING_FOR_OTHER_TEAM"};const processed=processSubmittedGame(game,a,b,queueState,latestHistory.items,latestDecisions.items,new Date().toISOString());if(!processed.ok)return{error:processed.error};saveGames(latestGames.items.map(g=>g.id===gameId?processed.game:g));if(processed.game.status==="INVALID_SCORE")return{outcome:"INVALID_SCORE"};saveHistory(processed.history);saveDecisions(processed.decisions);replaceQueueState(processed.queue);if(checkInState)replaceCheckInState(closeGameCheckInSession(checkInState,processed.game));notify("RESULT_SAVED",game.courtId);notify(processed.game.postGame?.winnerStatus==="RESTING"?"WINNER_RESTS":"WINNER_STAYS",game.courtId,processed.game.winnerTeamId);notify("REQUEUE_DECISION",game.courtId,processed.game.loserTeamId);return{outcome:"COMPLETED"}}
 function decide(gameId:string,requeue:boolean):GameLifecycleError|null{if(!decisionState||!queueState||!activeUserId)return"DECISION_NOT_FOUND";const decision=decisionState.items.find(d=>d.gameId===gameId);if(!decision)return"DECISION_NOT_FOUND";const result=requeue?chooseRequeue(decision,queueState,activeUserId,new Date().toISOString()):chooseLeaveQueue(decision,queueState,activeUserId,new Date().toISOString());if("error" in result)return result.error??"INVALID_GAME_STATUS";saveDecisions(decisionState.items.map(d=>d.id===decision.id?result.decision:d));replaceQueueState(result.queue);if(requeue)notify("REQUEUE_SUCCESS",decision.courtId,decision.teamId);return null}
 function decideWinner(gameId:string,continuePlaying:boolean):GameLifecycleError|null{if(!gameState||!queueState||!activeUserId)return"GAME_NOT_FOUND";const game=gameState.items.find((item)=>item.id===gameId);if(!game)return"GAME_NOT_FOUND";const result=chooseWinnerContinuation(game,queueState,activeUserId,continuePlaying,new Date().toISOString());if(result.error)return result.error;saveGames(gameState.items.map((item)=>item.id===gameId?result.game!:item));replaceQueueState(result.queue!);return null}
 function shortenDecision(gameId:string,seconds:number){if(!decisionState)return;const deadline=new Date(Date.now()+seconds*1000).toISOString();saveDecisions(decisionState.items.map(d=>d.gameId===gameId&&d.status==="DECIDING"?{...d,requeueDecisionDeadline:deadline}:d))}function expireDecision(gameId:string){if(!decisionState)return;const deadline=new Date(Date.now()-1).toISOString();saveDecisions(decisionState.items.map(d=>d.gameId===gameId&&d.status==="DECIDING"?{...d,requeueDecisionDeadline:deadline}:d))}
 function resetLifecycle(){const gs=gameRepo.reset();setGameState(gs);setScoreState(scoreRepo.reset());setHistoryState(statsRepo.reset());setDecisionState(decisionRepo.reset());setActiveUser(gs.items[0]?.teamA.captainUserId??null)}
 function setScenario(gameId:string,mode:"FIRST_WIN"|"SECOND_WIN"|"REST_GAME"|"RETURNING"){if(!gameState)return;saveGames(gameState.items.map(game=>game.id!==gameId?game:mode==="FIRST_WIN"?{...game,teamA:{...game.teamA,consecutiveWinsBefore:0},isRestGame:false}:mode==="SECOND_WIN"?{...game,teamA:{...game.teamA,consecutiveWinsBefore:1},isRestGame:false}:mode==="REST_GAME"?{...game,isRestGame:true,restingChampionTeamId:"queue-team-north"}: {...game,postGame:{winnerStatus:"RETURNING_CHAMPION",winnerConsecutiveWins:0,loserStatus:"LEFT_QUEUE",nextTeamIds:[game.teamA.teamId],returningChampionTeamId:game.teamA.teamId}}))}
 useEffect(()=>{if(!decisionState||!queueState)return;const timer=setInterval(()=>{let q=queueState,changed=false;const items=decisionState.items.map(d=>{const result=expireRequeueDecisionIfNeeded(d,q,new Date().toISOString());if(result.decision!==d){changed=true;q=result.queue;notify("REQUEUE_TIMEOUT",d.courtId,d.teamId)}return result.decision});if(changed){saveDecisions(items);replaceQueueState(q)}},1000);return()=>clearInterval(timer);// eslint-disable-next-line react-hooks/exhaustive-deps
 },[decisionState,queueState]);
 return <Ctx.Provider value={{ready:Boolean(gameState&&scoreState&&historyState&&decisionState),games:gameState?.items??[],submissions:scoreState?.items??[],history:historyState?.items??[],decisions:decisionState?.items??[],activeUserId,setActiveUser,requestEnd,cancelEnd,confirmEnd,saveDraft,submitScores,chooseWinnerContinue:(id)=>decideWinner(id,true),chooseWinnerLeave:(id)=>decideWinner(id,false),chooseRequeue:(id)=>decide(id,true),chooseLeave:(id)=>decide(id,false),shortenDecision,expireDecision,setScenario,resetLifecycle}}>{children}</Ctx.Provider>}
export function useGameLifecycle(){const value=useContext(Ctx);if(!value)throw new Error("useGameLifecycle must be used inside provider");return value}
