import type { DashboardLanguage } from "./dashboard-translations";

const shared = {
  sectionLabel: "TEAM CHECK-IN",
  devTitle: "Development tools",
} as const;

export const checkInTranslations = {
  th: {
    ...shared, title: "เช็กอินก่อนลงสนาม", calledTeam: "ทีมที่ถูกเรียก", timeRemaining: "เวลาที่เหลือ", expired: "หมดเวลาเช็กอิน", checkedIn: "เช็กอินแล้ว", notReady: "ยังไม่พร้อม", readyCount: "สมาชิกพร้อม", imReady: "ฉันพร้อม", cancelReady: "ยกเลิกความพร้อม", confirmTeamReady: "ยืนยันว่าทีมพร้อม", waitingCaptain: "รอหัวหน้าทีมยืนยันความพร้อม", teamReady: "ทีมพร้อมลงสนาม", missed: "พลาดคิว", missedHint: "เช็กอินไม่ครบภายในเวลาที่กำหนด ทีมถูกนำออกจากคิวแล้ว", rejoin: "กลับไปเข้าคิวใหม่", noCalledTeam: "ยังไม่มีทีมที่ถูกเรียก", location: "ตำแหน่งจำลอง", withinRange: "อยู่ในระยะ", outOfRange: "อยู่นอกระยะ", permissionDenied: "ไม่อนุญาตตำแหน่ง", devHint: "เครื่องมือจำลองสำหรับทดสอบเท่านั้น", callNext: "เรียกทีมถัดไป", shorten: "เหลือ 10 วินาที", expireNow: "หมดเวลาทันที", switchUser: "สลับผู้ใช้จำลอง", startGame: "เริ่มเกมจำลอง", reset: "Reset check-in", notifications: "การแจ้งเตือนจำลอง", noNotifications: "ยังไม่มีการแจ้งเตือน", TEAM_CALLED: "ทีมถูกเรียกแล้ว", ONE_MINUTE_LEFT: "เหลือเวลาเช็กอิน 1 นาที", TEAM_READY: "ทีมยืนยันความพร้อมแล้ว", MISSED_QUEUE: "ทีมพลาดคิว", GAME_READY: "เกมพร้อมเริ่ม", gamePlaying: "กำลังแข่งขัน", target: "เป้าหมาย", points: "แต้ม", error_NO_WAITING_TEAM: "ไม่มีทีม WAITING ในคิว", error_TEAM_ALREADY_CALLED: "มีทีมกำลังเช็กอินอยู่แล้ว", error_SESSION_NOT_FOUND: "ไม่พบรอบเช็กอินที่ใช้งานได้", error_MEMBER_NOT_IN_TEAM: "ผู้ใช้นี้ไม่ได้อยู่ในรายชื่อทีม", error_NOT_CAPTAIN: "เฉพาะหัวหน้าทีมเท่านั้นที่ยืนยันความพร้อมได้", error_ALREADY_CHECKED_IN: "สมาชิกเช็กอินแล้ว", error_NOT_CHECKED_IN: "สมาชิกยังไม่เช็กอิน", error_OUT_OF_RANGE: "สมาชิกทุกคนต้องอยู่ภายใน 50 เมตรจากสนาม", error_PERMISSION_DENIED: "สมาชิกบางคนไม่อนุญาตให้ตรวจตำแหน่งจำลอง", error_DEADLINE_EXPIRED: "หมดเวลาเช็กอินแล้ว", error_CANNOT_CANCEL: "ทีมพร้อมลงสนามแล้ว จึงยกเลิกไม่ได้", error_NOT_ENOUGH_READY_TEAMS: "ต้องมีสองทีมพร้อม หรือทีมครองสนามกับผู้ท้าชิงหนึ่งทีม", error_GAME_ALREADY_ACTIVE: "สนามนี้มีเกมกำลังแข่งขันอยู่", mockLocationNotice: "ตำแหน่งจำลองสำหรับ Development", status_CALLED: "ถูกเรียก", status_CHECKING_IN: "กำลังเช็กอิน", status_READY_TO_PLAY: "พร้อมลงสนาม", status_PLAYING: "กำลังแข่งขัน", status_MISSED_QUEUE: "พลาดคิว", status_WAITING: "รอคิว", status_CANCELLED: "ยกเลิก",
  },
  en: {
    ...shared, title: "Check in before playing", calledTeam: "Called team", timeRemaining: "Time remaining", expired: "Check-in expired", checkedIn: "Checked in", notReady: "Not ready", readyCount: "Members ready", imReady: "I'm ready", cancelReady: "Cancel readiness", confirmTeamReady: "Confirm team ready", waitingCaptain: "Waiting for the team captain", teamReady: "Team ready to play", missed: "Missed queue", missedHint: "The team did not complete check-in before the deadline and was removed from the active queue.", rejoin: "Join the queue again", noCalledTeam: "No team has been called", location: "Mock location", withinRange: "Within range", outOfRange: "Out of range", permissionDenied: "Permission denied", devHint: "Simulation controls for development only", callNext: "Call next team", shorten: "Set 10 seconds", expireNow: "Expire now", switchUser: "Switch mock user", startGame: "Start mock game", reset: "Reset check-in", notifications: "Mock notifications", noNotifications: "No notifications yet", TEAM_CALLED: "Team called", ONE_MINUTE_LEFT: "One minute left to check in", TEAM_READY: "Team readiness confirmed", MISSED_QUEUE: "Team missed queue", GAME_READY: "Game ready to start", gamePlaying: "Now playing", target: "Target", points: "points", error_NO_WAITING_TEAM: "No WAITING team in this queue", error_TEAM_ALREADY_CALLED: "A team is already checking in", error_SESSION_NOT_FOUND: "No active check-in session", error_MEMBER_NOT_IN_TEAM: "This user is not on the team roster", error_NOT_CAPTAIN: "Only the team captain can confirm readiness", error_ALREADY_CHECKED_IN: "Member has already checked in", error_NOT_CHECKED_IN: "Member has not checked in", error_OUT_OF_RANGE: "Every member must be within 50 metres of the court", error_PERMISSION_DENIED: "A member denied mock location permission", error_DEADLINE_EXPIRED: "The check-in deadline has passed", error_CANNOT_CANCEL: "The team is ready to play and readiness cannot be cancelled", error_NOT_ENOUGH_READY_TEAMS: "Two READY_TO_PLAY teams are required", error_GAME_ALREADY_ACTIVE: "A game is already active on this court", mockLocationNotice: "Development mock location", status_CALLED: "Called", status_CHECKING_IN: "Checking in", status_READY_TO_PLAY: "Ready to play", status_PLAYING: "Playing", status_MISSED_QUEUE: "Missed queue", status_WAITING: "Waiting", status_CANCELLED: "Cancelled",
  },
} as const satisfies Record<DashboardLanguage, Record<string, string>>;

export type CheckInCopy = (typeof checkInTranslations)[DashboardLanguage];
