import "server-only";
import type { SupabaseClient } from "@supabase/supabase-js";
import { getSupabaseQueueData, type SupabaseQueueData } from "./supabase-queue-repository";
import type { GameLifecycle, PlayerGameHistory } from "./game-lifecycle-types";
import type { CourtId } from "./queue-types";

type GameRow={id:string;court_id:CourtId;team_a_id:string;team_b_id:string;target_score:number;status:GameLifecycle["status"];started_at:string;winner_team_id:string|null;loser_team_id:string|null;final_team_a_score:number|null;final_team_b_score:number|null;completed_at:string|null};
type HistoryRow={game_id:string;user_id:string;team_id:string;format:PlayerGameHistory["teamType"];court_id:CourtId;completed_at:string;points:number;won:boolean};
export type SupabaseCourtEvent={id:string;title:string;details:string;startsAt:string;endsAt:string;allDay:boolean;impact:"LOW"|"MEDIUM"|"HIGH";courtIds:string[]};
export type SupabaseDashboardData={queue:SupabaseQueueData;games:GameLifecycle[];history:PlayerGameHistory[];events:SupabaseCourtEvent[];profile:{displayName:string;avatarUrl:string|null;role:"USER"|"ADMIN";initials:string}};
export async function getSupabaseDashboardData(supabase:SupabaseClient,userId:string):Promise<SupabaseDashboardData>{
 const[queue,gamesResult,historyResult,eventsResult]=await Promise.all([getSupabaseQueueData(supabase,userId),supabase.from("games").select("id,court_id,team_a_id,team_b_id,target_score,status,started_at,winner_team_id,loser_team_id,final_team_a_score,final_team_b_score,completed_at").in("status",["PLAYING","END_REQUESTED","AWAITING_SCORE","COMPLETED"]).order("started_at",{ascending:false}),supabase.from("player_game_history").select("game_id,user_id,team_id,format,court_id,completed_at,points,won").eq("user_id",userId).order("completed_at",{ascending:false}),supabase.from("court_events").select("id,title,details,starts_at,ends_at,all_day,court_event_courts(court_id)").is("cancelled_at",null).gte("ends_at",new Date().toISOString()).order("starts_at")]);
 const teamById=new Map(queue.teams.map(t=>[t.id,t]));
 const games=((gamesResult.data??[])as GameRow[]).map(row=>{const a=teamById.get(row.team_a_id);const b=teamById.get(row.team_b_id);return{id:row.id,courtId:row.court_id,teamA:{teamId:row.team_a_id,teamName:a?.name??"Unknown team",captainUserId:a?.captainUserId??"",members:a?.members??[],consecutiveWinsBefore:0},teamB:{teamId:row.team_b_id,teamName:b?.name??"Unknown team",captainUserId:b?.captainUserId??"",members:b?.members??[],consecutiveWinsBefore:0},targetScore:row.target_score,startedAt:row.started_at,status:row.status,isRestGame:false,...(row.winner_team_id?{winnerTeamId:row.winner_team_id}:{}),...(row.loser_team_id?{loserTeamId:row.loser_team_id}:{}),...(row.final_team_a_score!==null?{finalTeamAScore:row.final_team_a_score}:{}),...(row.final_team_b_score!==null?{finalTeamBScore:row.final_team_b_score}:{}),...(row.completed_at?{completedAt:row.completed_at}:{})}});
 const history=((historyResult.data??[])as HistoryRow[]).map(row=>({gameId:row.game_id,playerId:row.user_id,teamId:row.team_id,teamType:row.format,courtId:row.court_id,completedAt:row.completed_at,points:row.points,won:row.won}));
 const events=(eventsResult.data??[]).map(event=>({id:event.id,title:event.title,details:event.details,startsAt:event.starts_at,endsAt:event.ends_at,allDay:event.all_day,impact:"MEDIUM" as const,courtIds:(event.court_event_courts??[]).map((item:{court_id:string})=>item.court_id)}));
 const profile=queue.teamData.currentUser;return{queue,games,history,events,profile:{displayName:profile.displayName,avatarUrl:profile.avatarUrl,role:profile.role,initials:profile.initials}};
}
