import"server-only";import type{SupabaseClient}from"@supabase/supabase-js";import type{CourtId}from"./queue-types";
export type AdminMaintenanceRow={id:string;courtId:CourtId;category:string;details:string;imageUrl:string|null;status:"NEW"|"IN_PROGRESS"|"RESOLVED";adminNote:string|null;createdAt:string};
type MaintenanceFeedRow={id:string;court_id:string;category:string;details:string;image_path:string|null;status:"NEW"|"IN_PROGRESS"|"RESOLVED";admin_note:string|null;created_at:string};
export type MyMaintenanceRow={id:string;courtId:CourtId;category:string;details:string;status:"NEW"|"IN_PROGRESS"|"RESOLVED";adminNote:string|null;createdAt:string};
export type PublicMaintenanceRow={id:string;courtId:CourtId;category:string;details:string;status:"NEW"|"IN_PROGRESS"|"RESOLVED";adminNote:string|null;createdAt:string;updatedAt:string};
type PublicMaintenanceFeedRow={id:string;court_id:string;category:string;details:string;status:"NEW"|"IN_PROGRESS"|"RESOLVED";admin_note:string|null;created_at:string;updated_at:string};
export async function getPublicMaintenanceReports(s:SupabaseClient):Promise<PublicMaintenanceRow[]>{const{data,error}=await s.rpc("list_public_maintenance_status");if(error){if(error.code==="PGRST202"||error.code==="42883")return[];throw new Error(`PUBLIC_MAINTENANCE_FAILED: ${error.message}`)}return((data??[]) as PublicMaintenanceFeedRow[]).map(row=>({id:row.id,courtId:row.court_id as CourtId,category:row.category,details:row.details,status:row.status,adminNote:row.admin_note,createdAt:row.created_at,updatedAt:row.updated_at}))}
export async function getMyMaintenanceReports(s:SupabaseClient):Promise<MyMaintenanceRow[]>{const{data,error}=await s.rpc("list_my_maintenance_reports");if(error)throw new Error(`MY_MAINTENANCE_FAILED: ${error.message}`);return((data??[]) as MaintenanceFeedRow[]).map(row=>({id:row.id,courtId:row.court_id as CourtId,category:row.category,details:row.details,status:row.status,adminNote:row.admin_note,createdAt:row.created_at}))}
export async function getAdminMaintenanceReports(s:SupabaseClient):Promise<AdminMaintenanceRow[]>{const{data,error}=await s.rpc("admin_list_maintenance_reports");if(error)throw new Error(`MAINTENANCE_FEED_FAILED: ${error.message}`);return Promise.all(((data??[]) as MaintenanceFeedRow[]).map(async row=>{let imageUrl:string|null=null;if(row.image_path){const{data:signed}=await s.storage.from("maintenance-evidence").createSignedUrl(row.image_path,900);imageUrl=signed?.signedUrl??null}return{id:row.id,courtId:row.court_id as CourtId,category:row.category,details:row.details,imageUrl,status:row.status,adminNote:row.admin_note,createdAt:row.created_at}}))}
